@startuml
/'
依赖关系 : 用一条带箭头的虚线表示
    它描述一个对象在运行期会使用到另一个对象的关系
    与关联关系不同的是，依赖关系是一种临时性的关系
    它通常都是在运行期产生，并且随着运行场景的不同，依赖关系也d可能发生变化
    Y依赖于Z

    Y对象保存了Z对象的实例，但Y对象对Z对象没有操作，关联关系
    
    如果Y对象某个场景使用了Z对象的属性或者方法，Y依赖于Z
    依赖关系也有单向依赖和双向依赖之分
    双向依赖是一种非常不好的结构，应该保持单向依赖
'/
ClassY ..> ClassZ : Y 依赖于 Z
note left of ClassY :依赖关系用一条带箭头的虚线表示 

@enduml

