@startuml
/'
关联关系 : 关联关系是用一条直线表示的
    它描述不同对象之间的结构关系
    它在一段时间内将多个类的实例连接在一起
    关联关系是一种静态关系，通常与运行状态无管
    关联关系用来定义对象之间静态的、天然的结构
'/
Class路人甲 --  Class路人乙 : 互相知道
note "关联关系用一条\n直线表示关联关系" as N甲
Class路人丙 --> Class路人丁 : 丙知道丁 丁不知道丙

@enduml