@startuml
/'
包含关系 : 是用一条带箭头的虚线加版型<<include>>表示
    它特别用于用例模型，说明在执行基本用例的用例实例过程中插入的行为段
    包含用例总是的等待有抽象性质的，基本用例可控制与包含用例的关系，并
    可依赖于执行包含用例所得的结果，但基本用例和包含用例都不能访问对方的属性
    从这种意义上讲，包含用例是被封装的，它代表可在各种不同的基本用例中复用的行为
    1.从基本用例中分解出这样的行为:它对于了解基本用例的主要目的并不是必需的，
    只有它的结果才比较重要
    2.分解出两个或者更多用例所共有的行为

'/
note "用一条带箭头的虚线加版型<<include>>表示" as N
@enduml