@startuml

/'
扩展关系 : 是用一条带箭头的虚线加版型<<extends>>来表示
    它特别用于在用例模型中说明向基本用例中的某个扩展点插入扩展用例
    扩展表示的是“可选”，而不是”必需“，这意味着即使没有扩展用例，基本用例也是完整的
    如果没有基本用例，扩展用例是不能单独存在的
    使用扩展关系可能基于以下理由:
    1.表明用例的某一部分是可选的系统行为
    2.表明只在特定条件下才执行分支流
    3.表明可能有一组行为段，其中的一个或者多个段可以在基本用例的扩展点处插入
    4.表明多个基本用例中都有可能触发一个可选的分支流
'/


note "用一条带箭头的虚线加版型<<extends>>来表示" as N
@enduml